//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CustomerDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CustomerDepartment()
        {
            this.T_CustomerUser = new HashSet<T_CustomerUser>();
        }
    
        public long CustomerDepID { get; set; }
        public long CustomerID { get; set; }
        public string CustomerDepName { get; set; }
        public long ParentDep { get; set; }
    
        public virtual T_Customer T_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CustomerUser> T_CustomerUser { get; set; }
    }
}
