//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CustomerUser
    {
        public long CustomerUserID { get; set; }
        public string CustomerUserBH { get; set; }
        public string CustomerUserName { get; set; }
        public long CustomerID { get; set; }
        public long CustomerDepID { get; set; }
        public int UserTypeID { get; set; }
        public byte[] UserPhone { get; set; }
        public string UserAddress { get; set; }
        public string UserPwd { get; set; }
    
        public virtual T_CustomerDepartment T_CustomerDepartment { get; set; }
        public virtual T_CustomerUserType T_CustomerUserType { get; set; }
    }
}
