//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductTradeDaySummary
    {
        public long TradeID { get; set; }
        public System.DateTime TradeDate { get; set; }
        public long ProductID { get; set; }
        public int TradeMonth { get; set; }
        public int TradeYear { get; set; }
        public string TradeYearMon { get; set; }
        public long CustomerID { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> avgPrice { get; set; }
        public Nullable<decimal> TradeAmount { get; set; }
        public Nullable<decimal> TradeMoney { get; set; }
        public string TradeUnit { get; set; }
        public Nullable<decimal> TradeFee { get; set; }
    
        public virtual T_Product T_Product { get; set; }
    }
}
